In [2]:
import numpy as np

In [3]:
lst2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
arr2d = np.arange(1, 10).reshape(3, 3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# 파이썬 2차원 리스트의 원소별 접근
lst2d = [[c*11 for c in r] for r in lst2d]
lst2d

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]

## 슬라이싱과 인덱싱의 차원 차이

아래 연속한 두 코드는 같은 결과를 반환하는 듯 보이지만, 인덱싱은 차원을 하나 낮추는 효과가 있는 반면 슬라이싱은 원래 배열의 차원을 유지한다.

즉, ndim이 달라진다.

In [6]:
print(arr2d[:, 1:2])
print(arr2d[:, 1])
print()

print(arr2d[1:2, :])
print(arr2d[1, :])


[[2]
 [5]
 [8]]
[2 5 8]

[[4 5 6]]
[4 5 6]


## sum 함수의 매개변수 axis

ndarray에서 axis 번호는 겉에 있는 순서대로 0부터 시작한다.
예를 들어, 2차원 배열에서 행은 0, 열은 1이다.

axis 번호에 해당하는 축의 방향으로 연산을 진행한다.

In [7]:
arr3d = np.arange(27).reshape(3,3,3)
print(arr3d); print()

print(arr3d.sum(axis=0))
print(np.sum(arr3d, axis=0))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[27 30 33]
 [36 39 42]
 [45 48 51]]
[[27 30 33]
 [36 39 42]
 [45 48 51]]


In [8]:
np.array(arr2d.flat)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a = np.array([1, 2])
b = np.array([3, 4])

print(np.hstack((a, b)))
print(np.column_stack((a, b)))

[1 2 3 4]
[[1 3]
 [2 4]]


In [10]:
arr2d
arr2d[[True, False, False]]

array([[1, 2, 3]])

In [11]:
names = np.array([1, 2, 3])
mask = (names == 1) | (names == 2)

mask = ~mask
mask

array([False, False,  True])

In [12]:
arr = np.arange(6).reshape(3, 2)
print(arr)
print(np.where([True, False, True]))
print(np.where([True, False, True], 1, [True, True, False]))

[[0 1]
 [2 3]
 [4 5]]
(array([0, 2], dtype=int64),)
[1 1 1]


In [13]:
np.split(arr2d, [1], axis=0)
np.hsplit(arr2d, [1])

[array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

In [14]:
arr = np.arange(6)

arr1 = arr.reshape(3, 2)
arr2 = np.random.randn(3, 2)

np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.3993944 ,  2.0251621 ],
       [ 1.06218309,  1.8079409 ],
       [ 0.97008069,  0.49478751]])

In [15]:
a = np.array([1, 2])
b = np.array([3, 4])

# np.r_[]
# []를 array 주변에 씌우면 차원이 하나 늘어난 array가 반환된다.
print(np.r_[[a], [b]])

# []를 씌우지 않으면 기존 array와 같은 차원의 array가 반환된다.
print(np.r_[a, b])

# np.c_[]
print(np.c_[a, b])
print(np.c_[[a], [b]])

[[1 2]
 [3 4]]
[1 2 3 4]
[[1 3]
 [2 4]]
[[1 2 3 4]]


In [16]:
Value = np.array([[1,2,3,4],[2,5,6,7],[8,9,10,11],[12,13,14,15]])
 
Value1 = np.array([1])
 
Value2 = np.array([3,3,3,3])
 
Value3 = np.array([4,5,6,7]).reshape(4,1)
 
print(Value + Value1) #4x4 + 1
 
print(Value + Value2) #4x4 + 1x4
 
print(Value2 + Value3) #1x4 + 4x1


[[ 2  3  4  5]
 [ 3  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 4  5  6  7]
 [ 5  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]
[[ 7  7  7  7]
 [ 8  8  8  8]
 [ 9  9  9  9]
 [10 10 10 10]]


In [18]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[3, 4], [3, 5], [3, 5]])

print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [35]:
np.random.seed(12346)

arr = np.random.randint(100, size=(5, 5))
print(arr, '\n')
print(arr[::2], '\n')
arr[::2].sort(0)
print(arr[::2], '\n')
arr

[[31 44 20 29 78]
 [38 62 10 46  7]
 [32 53 38 10 69]
 [69 54 11 85 57]
 [28 14 83  5 96]] 

[[31 44 20 29 78]
 [32 53 38 10 69]
 [28 14 83  5 96]] 

[[28 14 20  5 69]
 [31 44 38 10 78]
 [32 53 83 29 96]] 



array([[28, 14, 20,  5, 69],
       [38, 62, 10, 46,  7],
       [31, 44, 38, 10, 78],
       [69, 54, 11, 85, 57],
       [32, 53, 83, 29, 96]])

In [36]:
range(10)

range(0, 10)